### ISSUE TITLE
Identifiers used in reservations besides DUID

### ISSUE THREAD

**Issue by ZagHe568** [dhcwg/yang#18]
Although DUID is a most obvious identifier for a client, in many cases it is useless for assigning static reservations because the server administrator doesn't know the DUID util the client contacts the server for the first time.
There are other options which can be considered to make a reservation, e.g. MAC address, Remote-id and Subscriber-id. The model should allow for using those (perhaps also some other identifiers) to make static reservations.

**Comment by bevolz** [comment]
How about generalizing this to just some client identifier and perhaps an enumerated type (DUID, Remote-ID, Subscriber-ID, mac-address, other)?

Note: You should keep the client-identifier (DUID) though since a server can record the DUID even if it uses an alternative identifier. The server must maintain the DUID since that is part of the 3315 protocol.


  *   Bernie

**Comment by ZagHe568** [comment]
Yes. I think we could just add 'mac-address', 'remote-id' and 'subscriber-id' as non-mandatory nodes under reserved-addresses/prefixes.
However, I still don't see what an administrator should do if he has no idea of the client's DUID when making reservations since DUID is mandatory here. (Maybe it doesn't need further discussions and is out of the scope of this yang model ?)
